version: '3'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./public:/app/public
    command: yarn start:dev
  postgres:
    image: postgis/postgis:12-master
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data